"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/nami_room.glb -o app/_components/nami_room.jsx -r public
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera, Html, useIntersect, useCursor, useVideoTexture } from "@react-three/drei";
import * as THREE from "three";

export function NamiRoom(props) {
  const videoTexture = useVideoTexture("/video/sample.mp4");
  console.log(videoTexture);
  const { nodes, materials } = useGLTF("/models/nami_room.glb");
  const meshRef = useRef();
  const [hovered, setHovered] = React.useState(false);
  useCursor(hovered);
  let color = hovered ? "red" : "blue";
  const handleClick = () => {
    window.location.href = "https://portfolio-nami2024.netlify.app/";
  };

  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={52.129}
        position={[2.24, 0.331, 2.085]}
        rotation={[-0.331, 0.877, 0.259]}
        // target={[-0.978, 10.615, -0.52]}
      />
      <mesh
        // ref={meshRef}
        geometry={nodes.Plane.geometry}
        material={new THREE.MeshBasicMaterial({ map: videoTexture })}
        // material={materials["Material.003"]}
        position={[-0.978, 1.615, -0.52]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.382, 0.407, 0.248]}
        onClick={handleClick}
        onPointerOver={(e) => {
          e.stopPropagation();
          setHovered(true);
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          setHovered(false);
        }}
      ></mesh>
      <mesh geometry={nodes.wall_shelf.geometry} material={materials.black_gray} position={[-0.846, 1.667, 0.531]} />
      <group position={[-0.846, 1.072, 0.403]} rotation={[0, Math.PI / 2, 0]} scale={0.419}>
        <mesh geometry={nodes.pc_monitor_1.geometry} material={materials.switch_black} />
        <mesh geometry={nodes.pc_monitor_2.geometry} material={materials["Material.017"]} />
      </group>
      <mesh
        geometry={nodes.wall_shelf001.geometry}
        material={materials.black_gray}
        position={[-0.888, 1.349, 0.531]}
        scale={[0.837, 1, 1]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials["Material.016"]}
        position={[-0.984, 1.121, -0.451]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.31, 0.329, 0.201]}
      />
      <mesh geometry={nodes.Cube.geometry} material={materials["deep navy"]} position={[0.001, 1.01, 0]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials["deep navy"]} position={[0, 1.024, 0]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.metallic_silver} position={[-0.002, 1.325, -1.1]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.wood} position={[0, 1.155, 0]} />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials.black_gray}
        position={[-0.685, 0.779, 0.431]}
        scale={[0.357, 0.514, 0.357]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials.black_gray}
        position={[-0.685, 0.725, 0.431]}
        scale={[0.357, 0.565, 0.357]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials.tiru_green}
        position={[-0.672, 0.645, 0.707]}
        scale={[0.357, 0.368, 0.357]}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.gold}
        position={[-0.355, 0.645, 0.707]}
        scale={0.009}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials.tiru_green}
        position={[-0.672, 0.494, 0.707]}
        scale={[0.357, 0.368, 0.357]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials.gold}
        position={[-0.355, 0.494, 0.707]}
        scale={0.009}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials.tiru_green}
        position={[-0.672, 0.343, 0.707]}
        scale={[0.357, 0.368, 0.357]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials.gold}
        position={[-0.355, 0.343, 0.707]}
        scale={0.009}
      />
      <mesh
        geometry={nodes.BézierCurve.geometry}
        material={materials.green}
        position={[0.942, 0.474, -0.699]}
        rotation={[0, 0, Math.PI / 2]}
        scale={0.145}
      />
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials.blown}
        position={[0.942, 0.474, -0.699]}
        scale={0.114}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials.black_gray}
        position={[0.942, 0.474, -0.699]}
        scale={0.132}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["choco.001"]}
        position={[0.942, 0.36, -0.699]}
        scale={0.132}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials.bblue}
        position={[-0.921, 1.803, 0.715]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials.white}
        position={[-0.921, 1.803, 0.715]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials.bblue}
        position={[-0.845, 1.709, 0.412]}
        rotation={[0, -0.624, 0]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials["Material.007"]}
        position={[-0.845, 1.709, 0.412]}
        rotation={[0, -0.624, 0]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube020.geometry}
        material={materials.tiru_green}
        position={[-0.921, 1.803, 0.66]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={materials.white}
        position={[-0.921, 1.803, 0.66]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={materials.white}
        position={[-0.921, 1.803, 0.6]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={materials.white}
        position={[-0.921, 1.803, 0.6]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube029.geometry}
        material={materials.bblue}
        position={[-0.934, 1.473, 0.426]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube030.geometry}
        material={materials.white}
        position={[-0.934, 1.473, 0.426]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube031.geometry}
        material={materials.tiru_green}
        position={[-0.934, 1.473, 0.377]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube032.geometry}
        material={materials.white}
        position={[-0.934, 1.473, 0.377]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube033.geometry}
        material={materials.white}
        position={[-0.934, 1.473, 0.323]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube034.geometry}
        material={materials.white}
        position={[-0.934, 1.473, 0.323]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube035.geometry}
        material={materials.bblue}
        position={[-0.934, 1.473, 0.585]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube036.geometry}
        material={materials.white}
        position={[-0.934, 1.473, 0.585]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube037.geometry}
        material={materials.tiru_green}
        position={[-0.934, 1.473, 0.536]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube040.geometry}
        material={materials.white}
        position={[-0.934, 1.473, 0.536]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube041.geometry}
        material={materials.white}
        position={[-0.934, 1.473, 0.483]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube042.geometry}
        material={materials.white}
        position={[-0.934, 1.473, 0.483]}
        rotation={[-Math.PI / 2, -1.528, Math.PI]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube043.geometry}
        material={materials.bblue}
        position={[-0.84, 1.39, 0.757]}
        rotation={[0, -0.624, 0]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube044.geometry}
        material={materials["Material.007"]}
        position={[-0.84, 1.39, 0.757]}
        rotation={[0, -0.624, 0]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube046.geometry}
        material={materials["bblue.001"]}
        position={[-0.759, 0.521, -0.748]}
        rotation={[0, -0.624, 0]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube047.geometry}
        material={materials["Material.007"]}
        position={[-0.759, 0.521, -0.748]}
        rotation={[0, -0.624, 0]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials.switch_black}
        position={[-0.582, 0.834, 0.574]}
        rotation={[-Math.PI, 1.564, -Math.PI]}
        scale={[0.012, 0.005, 0.012]}
      />
      <mesh
        geometry={nodes.keyboard.geometry}
        material={materials.metallic_silver}
        position={[-0.536, 0.821, 0.42]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube038.geometry}
        material={materials.black_gray}
        position={[-0.774, 0.463, -0.75]}
        scale={[0.178, 0.267, 0.178]}
      />
      <mesh
        geometry={nodes.Cube039.geometry}
        material={materials.tiru_green}
        position={[-0.774, 0.466, -0.75]}
        scale={0.178}
      />
      <mesh
        geometry={nodes.Cube028.geometry}
        material={materials.black_gray}
        position={[-0.774, 0.812, -0.75]}
        scale={[0.178, 0.263, 0.178]}
      />
      <mesh
        geometry={nodes.Cube045.geometry}
        material={materials.tiru_green}
        position={[-0.774, 0.741, -0.75]}
        scale={0.178}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials["choco.001"]}
        position={[0.414, 0.463, -0.242]}
        scale={0.313}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials["choco.001"]}
        position={[0.635, 0.33, -0.237]}
        scale={0.313}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials["choco.001"]}
        position={[0.201, 0.33, -0.237]}
        scale={0.313}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials["choco.001"]}
        position={[0.424, 0.33, -0.029]}
        scale={0.313}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials["choco.001"]}
        position={[0.424, 0.33, -0.448]}
        scale={0.313}
      />
      <mesh
        geometry={nodes.switch002.geometry}
        material={materials["switch_black.001"]}
        position={[0.311, 0.493, -0.482]}
        rotation={[Math.PI / 2, 0, 0.23]}
        scale={[0.019, 0.01, 0.02]}
      />
      <mesh
        geometry={nodes.switch001.geometry}
        material={materials["switch_white.001"]}
        position={[0.447, 0.513, -0.39]}
        rotation={[0, -0.23, 0]}
        scale={0.081}
      />
      <group position={[0.447, 0.513, -0.39]} rotation={[0, -0.23, 0]} scale={0.081}>
        <mesh geometry={nodes.Cube015_1.geometry} material={materials["switch_black.001"]} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials["switch_white.001"]} />
        <mesh geometry={nodes.Cube015_3.geometry} material={materials["switch.001"]} />
      </group>
      <mesh
        geometry={nodes.Circle002.geometry}
        material={materials.choco}
        position={[0.282, 0.607, -0.178]}
        rotation={[0.366, -1.449, 0.267]}
        scale={0.062}
      />
      <mesh
        geometry={nodes.Torus005.geometry}
        material={materials.gold}
        position={[0.372, 0.573, -0.192]}
        rotation={[0.152, -1.28, -1.522]}
        scale={0.039}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials.white}
        position={[0.284, 0.561, -0.182]}
        rotation={[0.366, -1.449, 0.267]}
        scale={0.076}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials.white}
        position={[0.463, 0.526, -0.123]}
        scale={[0.111, 0.051, 0.111]}
      />
      <mesh
        geometry={nodes.Torus012.geometry}
        material={materials.brown}
        position={[0.456, 0.537, -0.113]}
        scale={0.048}
      />
      <mesh
        geometry={nodes.Torus013.geometry}
        material={materials["choco.002"]}
        position={[0.456, 0.545, -0.113]}
        scale={0.048}
      />
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={materials.switch_black}
        position={[-0.066, 0.247, 0.828]}
        rotation={[-Math.PI / 2, 0, 2.461]}
        scale={[0.032, 0.018, 0.032]}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={materials.switch_black}
        position={[-0.3, 0.247, 0.642]}
        rotation={[-Math.PI / 2, 0, 1.097]}
        scale={[0.032, 0.018, 0.032]}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={materials.switch_black}
        position={[-0.196, 0.247, 0.362]}
        rotation={[-Math.PI / 2, 0, -1.364]}
        scale={[0.032, 0.018, 0.032]}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={materials.switch_black}
        position={[0.103, 0.247, 0.374]}
        rotation={[-Math.PI / 2, 0, -1.443]}
        scale={[0.032, 0.018, 0.032]}
      />
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={materials.switch_black}
        position={[0.183, 0.247, 0.662]}
        rotation={[-Math.PI / 2, 0, 2.405]}
        scale={[0.032, 0.018, 0.032]}
      />
      <mesh
        geometry={nodes.Cylinder018.geometry}
        material={materials.metallic_silver}
        position={[-0.055, 0.312, 0.574]}
        rotation={[Math.PI, -1.223, Math.PI]}
        scale={[0.042, 0.061, 0.042]}
      />
      <mesh
        geometry={nodes.Cube056.geometry}
        material={materials.switch_black}
        position={[-0.065, 0.786, 0.508]}
        rotation={[Math.PI, -1.223, Math.PI]}
        scale={[0.235, 0.03, 0.235]}
      />
      <mesh
        geometry={nodes.Cube057.geometry}
        material={materials.metallic_silver}
        position={[-0.061, 0.296, 0.724]}
        rotation={[-Math.PI, 0.033, -Math.PI]}
        scale={[0.03, 0.024, 0.115]}
      />
      <mesh
        geometry={nodes.Cube058.geometry}
        material={materials.metallic_silver}
        position={[-0.2, 0.296, 0.615]}
        rotation={[-Math.PI, 1.29, -Math.PI]}
        scale={[0.03, 0.024, 0.115]}
      />
      <mesh
        geometry={nodes.Cube059.geometry}
        material={materials.metallic_silver}
        position={[-0.139, 0.296, 0.448]}
        rotation={[0, 0.595, 0]}
        scale={[0.03, 0.024, 0.115]}
      />
      <mesh
        geometry={nodes.Cube060.geometry}
        material={materials.metallic_silver}
        position={[0.038, 0.296, 0.455]}
        rotation={[0, -0.662, 0]}
        scale={[0.03, 0.024, 0.115]}
      />
      <mesh
        geometry={nodes.Cube061.geometry}
        material={materials.metallic_silver}
        position={[0.086, 0.296, 0.625]}
        rotation={[Math.PI, -1.223, Math.PI]}
        scale={[0.03, 0.024, 0.115]}
      />
      <mesh
        geometry={nodes.Cube062.geometry}
        material={materials.metallic_silver}
        position={[-0.041, 0.582, 0.517]}
        rotation={[Math.PI, -1.223, Math.PI]}
        scale={[0.132, 0.017, 0.132]}
      />
      <mesh
        geometry={nodes.Cube063.geometry}
        material={materials.switch_black}
        position={[-0.041, 0.651, 0.517]}
        rotation={[Math.PI, -1.223, Math.PI]}
        scale={[0.235, 0.042, 0.235]}
      />
      <mesh
        geometry={nodes.Cube064.geometry}
        material={materials.switch_black}
        position={[0.091, 0.834, 0.15]}
        rotation={[Math.PI, -1.223, Math.PI]}
        scale={[0.237, 0.172, 0.237]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials.switch_black}
        position={[-0.805, 0.862, -0.764]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={materials.woody}
        position={[-0.792, 0.946, -0.765]}
        rotation={[-0.028, 0.092, 0.121]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={materials.woody}
        position={[-0.759, 0.963, -0.762]}
        rotation={[-0.042, -0.286, -0.025]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={materials.woody}
        position={[-0.752, 0.951, -0.782]}
        rotation={[-0.156, -0.343, -0.198]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials.Material}
        position={[0.074, 0.354, -0.805]}
        rotation={[0, -1.146, -0.798]}
        scale={0.215}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials.white}
        position={[-0.001, 1.842, -0.965]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.036, 0.431, 0.036]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={materials.white}
        position={[-0.001, 1.552, -0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.419, 0.419, 0.256]}
      />
    </group>
  );
}

useGLTF.preload("/models/nami_room.glb");
