/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/nami_room.glb -o app/_components/nami_room.jsx -r public
*/

import * as THREE from "three";
import React, { useEffect, useState } from "react";

import { useGLTF, useProgress, useVideoTexture } from "@react-three/drei";
import { useRef } from "react";
import gsap from "gsap";

export function NamiRoom({
  isScreenClicked,
  setIsScreenClicked,
}: {
  isScreenClicked: boolean;
  setIsScreenClicked: (isScreenClicked: boolean) => void;
}) {
  const videoTexture = useVideoTexture("/video/test.mp4");
  const [videoMaterial, setVideoMaterial] = useState<THREE.MeshBasicMaterial | null>(null);
  const { nodes, materials } = useGLTF("/models/nami_room_new.glb") as any;
  const groupRef = useRef<THREE.Group>(null);
  const pcScreenRef = useRef<THREE.Mesh>(null);
  const [hover, setHover] = useState(false);
  const { progress } = useProgress();

  useEffect(() => {
    if (progress === 100 && groupRef.current) {
      // 初期状態を設定
      groupRef.current.rotation.x = Math.PI / 4; // 45度上に傾ける
      groupRef.current.rotation.y = -Math.PI / 2; // 下側から開始
      groupRef.current.position.y = -2; // 下に配置

      // アニメーション
      gsap.to(groupRef.current.rotation, {
        x: 0,
        y: 0,
        duration: 3,
        ease: "power2.out",
      });

      gsap.to(groupRef.current.position, {
        y: 0,
        duration: 2,
        ease: "power2.out",
      });
    }
  }, [progress]);

  useEffect(() => {
    if (videoTexture) {
      const material = new THREE.MeshBasicMaterial({
        map: videoTexture,
        side: THREE.DoubleSide,
        transparent: true,
      });
      videoTexture.flipY = false; // テクスチャを反転
      setVideoMaterial(material);
    }
  }, [videoTexture]);

  useEffect(() => {
    if (pcScreenRef.current) {
      const material = pcScreenRef.current.material as THREE.MeshStandardMaterial;

      gsap.to(material, {
        emissive: hover ? new THREE.Color("#4a90e2") : new THREE.Color("#000000"),
        emissiveIntensity: hover ? 0.5 : 0,
        duration: 0.3,
        ease: "power2.out",
      });

      gsap.to(material, {
        color: hover ? new THREE.Color("#ffffff") : new THREE.Color("#cccccc"),
        duration: 0.3,
        ease: "power2.out",
      } as any);
    }
  }, [hover]);
  return (
    <group ref={groupRef} dispose={null}>
      <mesh
        geometry={nodes.poster_nami.geometry}
        material={materials["Material.003"]}
        position={[-0.99, 1.683, -0.483]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.454, 0.231, 0.255]}
      />
      <mesh geometry={nodes.wall_shelf.geometry} material={materials.woody} position={[-0.846, 1.72, 0.531]} />
      <mesh
        geometry={nodes.wall_shelf001.geometry}
        material={materials.woody}
        position={[-0.888, 1.402, 0.531]}
        scale={[0.837, 1, 1]}
      />
      <mesh
        geometry={nodes.poster_sakaba.geometry}
        material={materials["Material.016"]}
        position={[-0.997, 1.115, -0.483]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.454, 0.231, 0.255]}
      />
      <mesh
        geometry={nodes.pc_screen.geometry}
        position={[-0.826, 1.108, 0.428]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.277, 0.347, 0.156]}
        material={videoMaterial || materials["Material.009"]}
        onClick={() => setIsScreenClicked(true)}
        onPointerEnter={() => setHover(true)}
        onPointerLeave={() => setHover(false)}
      />
      <mesh
        geometry={nodes.pc_frame.geometry}
        material={materials.switch_black}
        position={[-0.833, 1.108, 0.428]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.305, 0.381, 0.172]}
      />
      <mesh
        geometry={nodes.pc_base.geometry}
        material={materials.switch_black}
        position={[-0.805, 0.829, 0.444]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.347, 0.347, 0.091]}
      />
      <mesh geometry={nodes.Cube.geometry} material={materials["deep navy"]} position={[0.001, 1.01, 0]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials["deep navy"]} position={[0, 1.024, 0]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.woody} position={[-0.002, 1.325, -1.1]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.wood} position={[0, 1.155, 0]} />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials.woody}
        position={[-0.685, 0.779, 0.431]}
        scale={[0.357, 0.514, 0.357]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials.woody}
        position={[-0.685, 0.725, 0.431]}
        scale={[0.357, 0.565, 0.357]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials.white}
        position={[-0.672, 0.645, 0.707]}
        scale={[0.357, 0.368, 0.357]}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.gold}
        position={[-0.355, 0.645, 0.707]}
        scale={0.009}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials.white}
        position={[-0.672, 0.494, 0.707]}
        scale={[0.357, 0.368, 0.357]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials.gold}
        position={[-0.355, 0.494, 0.707]}
        scale={0.009}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials.white}
        position={[-0.672, 0.343, 0.707]}
        scale={[0.357, 0.368, 0.357]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials.gold}
        position={[-0.355, 0.343, 0.707]}
        scale={0.009}
      />
      <mesh
        geometry={nodes.BézierCurve.geometry}
        material={materials.green}
        position={[0.801, 0.52, -0.699]}
        rotation={[0, 0, Math.PI / 2]}
        scale={0.145}
      />
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials.blown}
        position={[0.801, 0.52, -0.699]}
        scale={0.114}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials.black_gray}
        position={[0.801, 0.52, -0.699]}
        scale={0.132}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.001"]}
        position={[0.801, 0.407, -0.699]}
        scale={0.132}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials.bblue}
        position={[-0.92, 1.853, 0.715]}
        rotation={[-1.419, -1.553, -3.029]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials.white}
        position={[-0.92, 1.853, 0.715]}
        rotation={[-1.419, -1.553, -3.029]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials.bblue}
        position={[-0.845, 1.761, 0.412]}
        rotation={[0, -0.624, 0]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials["Material.007"]}
        position={[-0.845, 1.761, 0.412]}
        rotation={[0, -0.624, 0]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube020.geometry}
        material={materials.tiru_green}
        position={[-0.921, 1.851, 0.66]}
        rotation={[-2.28, -1.547, 2.393]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={materials.white}
        position={[-0.921, 1.851, 0.66]}
        rotation={[-1.419, -1.553, -3.029]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={materials.white}
        position={[-0.921, 1.853, 0.6]}
        rotation={[-1.615, -1.553, 3.058]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={materials.white}
        position={[-0.921, 1.853, 0.6]}
        rotation={[-1.615, -1.553, 3.058]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube029.geometry}
        material={materials.bblue}
        position={[-0.935, 1.521, 0.426]}
        rotation={[-1.45, -1.55, -3.056]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube030.geometry}
        material={materials.white}
        position={[-0.935, 1.521, 0.426]}
        rotation={[-1.45, -1.55, -3.056]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube031.geometry}
        material={materials.tiru_green}
        position={[-0.935, 1.518, 0.377]}
        rotation={[-1.45, -1.55, -3.056]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube032.geometry}
        material={materials.white}
        position={[-0.935, 1.518, 0.377]}
        rotation={[-1.45, -1.55, -3.056]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube033.geometry}
        material={materials.white}
        position={[-0.935, 1.52, 0.323]}
        rotation={[-1.45, -1.55, -3.056]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube034.geometry}
        material={materials.white}
        position={[-0.935, 1.52, 0.323]}
        rotation={[-1.45, -1.55, -3.056]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube035.geometry}
        material={materials.bblue}
        position={[-0.934, 1.516, 0.585]}
        rotation={[-1.45, -1.55, -3.056]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube036.geometry}
        material={materials.white}
        position={[-0.934, 1.516, 0.585]}
        rotation={[-1.45, -1.55, -3.056]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube037.geometry}
        material={materials.tiru_green}
        position={[-0.934, 1.517, 0.536]}
        rotation={[-1.45, -1.55, -3.056]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube040.geometry}
        material={materials.white}
        position={[-0.934, 1.517, 0.536]}
        rotation={[-1.45, -1.55, -3.056]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube041.geometry}
        material={materials.white}
        position={[-0.934, 1.515, 0.483]}
        rotation={[-1.45, -1.55, -3.056]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube042.geometry}
        material={materials.white}
        position={[-0.934, 1.515, 0.483]}
        rotation={[-1.45, -1.55, -3.056]}
        scale={[0.089, 0.02, 0.053]}
      />
      <mesh
        geometry={nodes.Cube043.geometry}
        material={materials.bblue}
        position={[-0.84, 1.443, 0.757]}
        rotation={[0, -0.624, 0]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube044.geometry}
        material={materials["Material.007"]}
        position={[-0.84, 1.443, 0.757]}
        rotation={[0, -0.624, 0]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube046.geometry}
        material={materials.bblue}
        position={[-0.669, 0.521, -0.776]}
        rotation={[0, -0.624, 0]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube047.geometry}
        material={materials["Material.007"]}
        position={[-0.669, 0.521, -0.776]}
        rotation={[0, -0.624, 0]}
        scale={[0.099, 0.022, 0.059]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials.metallic_silver}
        position={[-0.657, 0.834, 0.574]}
        rotation={[-Math.PI, 1.564, -Math.PI]}
        scale={[0.012, 0.005, 0.012]}
      />
      <mesh
        geometry={nodes.keyboard.geometry}
        material={materials["deep navy"]}
        position={[-0.611, 0.821, 0.42]}
        scale={[1.269, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube038.geometry}
        material={materials.white}
        position={[-0.774, 0.463, -0.75]}
        scale={[0.178, 0.267, 0.178]}
      />
      <mesh
        geometry={nodes.Cube039.geometry}
        material={materials["Material.015"]}
        position={[-0.774, 0.466, -0.75]}
        scale={0.178}
      />
      <mesh
        geometry={nodes.Cube028.geometry}
        material={materials.white}
        position={[-0.774, 0.812, -0.75]}
        scale={[0.178, 0.263, 0.178]}
      />
      <mesh
        geometry={nodes.Cube045.geometry}
        material={materials["Material.015"]}
        position={[-0.774, 0.741, -0.75]}
        scale={0.178}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials.woody}
        position={[0.36, 0.463, -0.382]}
        scale={0.313}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials.white}
        position={[0.581, 0.33, -0.377]}
        scale={0.313}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[0.147, 0.33, -0.377]}
        scale={0.313}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        position={[0.37, 0.33, -0.17]}
        scale={0.313}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={nodes.Cylinder006.material}
        position={[0.37, 0.33, -0.589]}
        scale={0.313}
      />
      <group position={[0.346, 0.269, -0.396]} scale={0.472}>
        <mesh geometry={nodes.Plane003.geometry} material={materials["Material.015"]} />
        <mesh geometry={nodes.Plane003_1.geometry} material={materials.white} />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials["deep navy"]} />
      </group>
      <mesh
        geometry={nodes.Circle002.geometry}
        material={materials.choco}
        position={[0.333, 0.603, -0.409]}
        rotation={[0.684, -1.453, 0.703]}
        scale={0.062}
      />
      <mesh
        geometry={nodes.Torus005.geometry}
        material={materials.gold}
        position={[0.425, 0.571, -0.416]}
        rotation={[0.2, -1.301, -1.351]}
        scale={0.039}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials.white}
        position={[0.336, 0.556, -0.408]}
        rotation={[0.684, -1.453, 0.703]}
        scale={0.076}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials["Material.001"]}
        position={[-0.805, 0.862, -0.764]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={materials.woody}
        position={[-0.792, 0.946, -0.765]}
        rotation={[-0.028, 0.092, 0.121]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={materials.woody}
        position={[-0.759, 0.963, -0.762]}
        rotation={[-0.042, -0.286, -0.025]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={materials.woody}
        position={[-0.752, 0.951, -0.782]}
        rotation={[-0.156, -0.343, -0.198]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials.white}
        position={[-0.069, 0.372, -0.794]}
        rotation={[0, -1.146, -0.798]}
        scale={0.215}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials.white}
        position={[-0.001, 1.842, -0.965]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.036, 0.431, 0.036]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={materials.white}
        position={[-0.001, 1.552, -0.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.419, 0.419, 0.256]}
      />
      <mesh
        geometry={nodes.Cube056.geometry}
        material={materials["deep navy"]}
        position={[-0.063, 0.738, 0.343]}
        rotation={[Math.PI, -1.223, Math.PI]}
        scale={[0.207, 0.026, 0.207]}
      />
      <mesh
        geometry={nodes.Cube057.geometry}
        material={materials.white}
        position={[-0.059, 0.307, 0.533]}
        rotation={[-Math.PI, 0.033, -Math.PI]}
        scale={[0.027, 0.021, 0.101]}
      />
      <mesh
        geometry={nodes.Cube058.geometry}
        material={materials.white}
        position={[-0.181, 0.307, 0.437]}
        rotation={[-Math.PI, 1.29, -Math.PI]}
        scale={[0.027, 0.021, 0.101]}
      />
      <mesh
        geometry={nodes.Cube059.geometry}
        material={nodes.Cube059.material}
        position={[-0.128, 0.307, 0.291]}
        rotation={[0, 0.595, 0]}
        scale={[0.027, 0.021, 0.101]}
      />
      <mesh
        geometry={nodes.Cube060.geometry}
        material={nodes.Cube060.material}
        position={[0.028, 0.307, 0.296]}
        rotation={[0, -0.662, 0]}
        scale={[0.027, 0.021, 0.101]}
      />
      <mesh
        geometry={nodes.Cube061.geometry}
        material={nodes.Cube061.material}
        position={[0.071, 0.307, 0.446]}
        rotation={[Math.PI, -1.223, Math.PI]}
        scale={[0.027, 0.021, 0.101]}
      />
      <mesh
        geometry={nodes.Cube062.geometry}
        material={materials["deep navy"]}
        position={[-0.041, 0.559, 0.351]}
        rotation={[Math.PI, -1.223, Math.PI]}
        scale={[0.116, 0.015, 0.116]}
      />
      <mesh
        geometry={nodes.Cube063.geometry}
        material={nodes.Cube063.material}
        position={[-0.041, 0.62, 0.351]}
        rotation={[Math.PI, -1.223, Math.PI]}
        scale={[0.207, 0.037, 0.207]}
      />
      <mesh
        geometry={nodes.Cube064.geometry}
        material={nodes.Cube064.material}
        position={[0.074, 0.78, 0.029]}
        rotation={[Math.PI, -1.223, Math.PI]}
        scale={[0.208, 0.151, 0.208]}
      />
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={materials["deep navy"]}
        position={[-0.063, 0.265, 0.624]}
        rotation={[-Math.PI / 2, 0, 2.461]}
        scale={[0.028, 0.016, 0.028]}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={materials["deep navy"]}
        position={[-0.269, 0.265, 0.461]}
        rotation={[-Math.PI / 2, 0, 1.097]}
        scale={[0.028, 0.016, 0.028]}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={materials["deep navy"]}
        position={[-0.178, 0.265, 0.214]}
        rotation={[-Math.PI / 2, 0, -1.364]}
        scale={[0.028, 0.016, 0.028]}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={materials["deep navy"]}
        position={[0.085, 0.265, 0.225]}
        rotation={[-Math.PI / 2, 0, -1.443]}
        scale={[0.028, 0.016, 0.028]}
      />
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={materials["deep navy"]}
        position={[0.156, 0.265, 0.479]}
        rotation={[-Math.PI / 2, 0, 2.405]}
        scale={[0.028, 0.016, 0.028]}
      />
      <mesh
        geometry={nodes.Cylinder018.geometry}
        material={materials["deep navy"]}
        position={[-0.054, 0.322, 0.401]}
        rotation={[Math.PI, -1.223, Math.PI]}
        scale={[0.037, 0.054, 0.037]}
      />
      <mesh geometry={nodes.Cube010.geometry} material={materials.metallic_silver} position={[-0.603, 0.837, -0.058]} />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials.switch_black}
        position={[-0.627, 0.849, 0.139]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials.tiru_green}
        position={[-0.854, 0.891, 0.73]}
        rotation={[0.064, 0.488, 0.091]}
        scale={[0.059, 0.058, 0.059]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials.tiru_green}
        position={[-0.833, 0.892, 0.751]}
        rotation={[-2.711, -1.346, -2.497]}
        scale={[0.059, 0.067, 0.059]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials.tiru_green}
        position={[-0.857, 0.896, 0.757]}
        rotation={[-Math.PI, 0.623, -Math.PI]}
        scale={[0.053, 0.059, 0.057]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={materials.tiru_green}
        position={[-0.843, 0.885, 0.76]}
        rotation={[Math.PI, -0.425, Math.PI]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials.tiru_green}
        position={[-0.865, 0.895, 0.744]}
        rotation={[-0.802, 1.475, 0.801]}
        scale={[0.059, 0.069, 0.059]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={materials.tiru_green}
        position={[-0.835, 0.89, 0.731]}
        rotation={[0, -0.623, 0]}
        scale={0.059}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials.white}
        position={[-0.847, 0.828, 0.747]}
        rotation={[0, 0.425, 0]}
        scale={0.059}
      />
      <mesh
        geometry={nodes.Circle001.geometry}
        material={materials.blown}
        position={[-0.847, 0.886, 0.747]}
        rotation={[0, 0.425, 0]}
        scale={0.046}
      />
      <group position={[0.704, 1.606, -0.98]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.159}>
        <mesh geometry={nodes.Cylinder016_1.geometry} material={materials["deep navy"]} />
        <mesh geometry={nodes.Cylinder016_2.geometry} material={materials.white} />
      </group>
    </group>
  );
}

useGLTF.preload("/models/nami_room.glb");
